# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\src\change_name_dlg_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeDialog(object):
    def setupUi(self, ChangeDialog):
        ChangeDialog.setObjectName("ChangeDialog")
        ChangeDialog.resize(465, 125)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ChangeDialog.sizePolicy().hasHeightForWidth())
        ChangeDialog.setSizePolicy(sizePolicy)
        ChangeDialog.setMinimumSize(QtCore.QSize(465, 125))
        ChangeDialog.setMaximumSize(QtCore.QSize(465, 125))
        self.buttonBox = QtWidgets.QDialogButtonBox(ChangeDialog)
        self.buttonBox.setGeometry(QtCore.QRect(299, 92, 156, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(ChangeDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 445, 76))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_cam_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_cam_id.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_cam_id.sizePolicy().hasHeightForWidth())
        self.line_cam_id.setSizePolicy(sizePolicy)
        self.line_cam_id.setMinimumSize(QtCore.QSize(150, 0))
        self.line_cam_id.setMaximumSize(QtCore.QSize(100, 16777215))
        self.line_cam_id.setReadOnly(True)
        self.line_cam_id.setObjectName("line_cam_id")
        self.verticalLayout.addWidget(self.line_cam_id)
        self.line_old = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_old.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_old.sizePolicy().hasHeightForWidth())
        self.line_old.setSizePolicy(sizePolicy)
        self.line_old.setMinimumSize(QtCore.QSize(350, 20))
        self.line_old.setMaximumSize(QtCore.QSize(350, 16777215))
        self.line_old.setReadOnly(True)
        self.line_old.setObjectName("line_old")
        self.verticalLayout.addWidget(self.line_old)
        self.line_new = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_new.setMinimumSize(QtCore.QSize(350, 20))
        self.line_new.setMaximumSize(QtCore.QSize(350, 300))
        self.line_new.setObjectName("line_new")
        self.verticalLayout.addWidget(self.line_new)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 3, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)

        self.retranslateUi(ChangeDialog)
        self.buttonBox.accepted.connect(ChangeDialog.accept)
        self.buttonBox.rejected.connect(ChangeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ChangeDialog)

    def retranslateUi(self, ChangeDialog):
        _translate = QtCore.QCoreApplication.translate
        ChangeDialog.setWindowTitle(_translate("ChangeDialog", "Change image name..."))
        self.label_3.setText(_translate("ChangeDialog", "Camera:"))
        self.label.setText(_translate("ChangeDialog", "Old image name:"))
        self.label_2.setText(_translate("ChangeDialog", "New image name:"))
