# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MonoPlotDialog
                                 A QGIS plugin
 Monoplotting of images
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-12
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Sebastian Mikolka-Flöry
        email                : sebastian.floery@geo.tuwien.ac.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5 import uic
from PyQt5 import QtWidgets
from PyQt5.QtCore import pyqtSignal
from .src.orient_dlg_base import Ui_Dialog

#as we create new ui.py file, these lines need to be commented
# https://gis-ops.com/qgis-3-plugin-tutorial-plugin-development-explained-part-2/
# FORM_CLASS, _ = uic.loadUiType(os.path.join(
#     os.path.dirname(__file__), 'mono_plot_dialog_base.ui'))


class OrientDialog(QtWidgets.QDialog, Ui_Dialog):
    
    closed = pyqtSignal()
    
    def __init__(self, parent=None):
        """Constructor."""
        super(OrientDialog, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def closeEvent(self, event):
        self.closed.emit()