# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MonoPlot
                                 A QGIS plugin
 Monoplotting of images
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-12
        copyright            : (C) 2021 by Sebastian Mikolka-Flöry
        email                : sebastian.floery@geo.tuwien.ac.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MonoPlot class from file MonoPlot.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .main import MonoPlot
    return MonoPlot(iface)
