# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MoniQue
                                 A QGIS plugin
 Monoplotting oblique images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-07
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Sebastian Mikolka-Flöry
        email                : s.floery@gmx.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import Qt, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QApplication, QFileDialog

from qgis.core import QgsProject, QgsVectorLayer, QgsJsonUtils, QgsVectorLayer, QgsField, NULL
from qgis.gui import QgsMapToolPan

# # Initialize Qt resources from file resources.py
# from .resources import *
from .gui.dlg_main import MainDialog
# from .gui.dlg_convert import ConvertDialog

import os.path
import json
import open3d as o3d
import numpy as np 
import xml.etree.ElementTree as ET
import glob

from .camera import Camera

class MoniQue:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.iface.actionMapTips().trigger()    #enable showing map tips
        
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        self.icon_dir = os.path.join(self.plugin_dir, "gfx", "icon")
        
        self.project_name = None
        
        #paths to the styling files
        self.cam_qml_path = os.path.join(self.plugin_dir, "gfx", "qml", "camera.qml")
        self.img_line_qml_path = os.path.join(self.plugin_dir, "gfx", "qml", "lines_img.qml")
        self.map_line_qml_path = os.path.join(self.plugin_dir, "gfx", "qml", "lines_map.qml")
        self.map_region_qml_path = os.path.join(self.plugin_dir, "gfx", "qml", "region_map.qml")
        self.map_gcps_qml_path = os.path.join(self.plugin_dir, "gfx", "qml", "gcps_map.qml")
        self.img_gcps_qml_path = os.path.join(self.plugin_dir, "gfx", "qml", "gcps_img.qml")
        self.map_line_vx_qml_path = os.path.join(self.plugin_dir, "gfx", "qml", "lines_map_vx.qml")
        #map_canvas is the canvas of the QGIS main window
        self.map_canvas = iface.mapCanvas()
        
        self.camera_collection = {}
        
        #set tools
        self.map_pan_tool = QgsMapToolPan(self.map_canvas)

        # Declare instance attributes
        self.actions = []
    
    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        launch_icon = QIcon(os.path.join(self.plugin_dir, "icon.png"))
        launch_action = QAction(launch_icon, 'Run moniQue...', self.iface.mainWindow())
        launch_action.triggered.connect(self.open_main_dlg)
        launch_action.setEnabled(True)
        
        # convert_icon = QIcon(os.path.join(self.icon_dir, "mActionAddMeshLayer.png"))
        # convert_action = QAction(convert_icon, "Convert DTM to mesh...", self.iface.mainWindow())
        # convert_action.triggered.connect(self.open_convert_dlg)
        # convert_action.setEnabled(True)
        
        self.iface.addPluginToMenu("moniQue", launch_action)
        # self.iface.addPluginToMenu("moniQue", convert_action)
        
        self.iface.addToolBarIcon(launch_action)
        
        self.actions.append(launch_action)
        # self.actions.append(convert_action)

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu('moniQue', action)
            self.iface.removeToolBarIcon(action)

    def on_load_project_signal(self, data):
        
        self.gpkg_path = data["gpkg_path"]
        self.project_name = os.path.basename(self.gpkg_path).rsplit(".")[0]
        
        QApplication.instance().setOverrideCursor(Qt.WaitCursor)
        
        self.reset_plugin()
        
        #load layers from geopackage
        gpkg_reg_lyr = self.gpkg_path + "|layername=region"
        self.reg_lyr = QgsVectorLayer(gpkg_reg_lyr, "region", "ogr")
        self.reg_lyr.setProviderEncoding(u'UTF-8')
        self.reg_lyr.dataProvider().setEncoding(u'UTF-8')
        self.reg_lyr.loadNamedStyle(self.map_region_qml_path)
                
        gpkg_cam_lyr = self.gpkg_path + "|layername=cameras"
        self.cam_lyr = QgsVectorLayer(gpkg_cam_lyr, "cameras", "ogr")           
        self.cam_lyr.setProviderEncoding(u'UTF-8')
        self.cam_lyr.dataProvider().setEncoding(u'UTF-8')
        self.cam_lyr.loadNamedStyle(self.cam_qml_path)
        
        #add missing fields to vertex layer in case they are not present
        cam_lyr_pr = self.cam_lyr.dataProvider()
        field_names = [field.name() for field in cam_lyr_pr.fields()]
        
        pot_fields = {"min_d_mono": QgsField("min_d_mono", QVariant.Double, "double", 6, 3),
                      "xx_std": QgsField("xx_std", QVariant.Double, "double", 6, 3),
                      "yy_std": QgsField("yy_std", QVariant.Double, "double", 6, 3),
                      "nr_trials": QgsField("nr_trials", QVariant.Int)}
        
        add_fields = []        
        for name, qfield in pot_fields.items():
            if name not in field_names:
                add_fields.append(qfield)
        
        cam_lyr_pr.addAttributes(add_fields)
        self.cam_lyr.updateFields() 
        
        mono_idx = self.cam_lyr.fields().indexOf('min_d_mono')
        xx_idx = self.cam_lyr.fields().indexOf('xx_std')
        yy_idx = self.cam_lyr.fields().indexOf('yy_std')
        trials_idx = self.cam_lyr.fields().indexOf("nr_trials")
        
        for feat in self.cam_lyr.getFeatures():
            if feat[mono_idx] == NULL:
                self.cam_lyr.startEditing()
                self.cam_lyr.changeAttributeValue(feat.id(), mono_idx, 100)
                self.cam_lyr.commitChanges()
                
            if feat[xx_idx] == NULL:
                self.cam_lyr.startEditing()
                self.cam_lyr.changeAttributeValue(feat.id(), xx_idx, 1) 
                self.cam_lyr.commitChanges()
            
            if feat[yy_idx] == NULL:
                self.cam_lyr.startEditing()
                self.cam_lyr.changeAttributeValue(feat.id(), yy_idx, 1) 
                self.cam_lyr.commitChanges()

            if feat[trials_idx] == NULL:
                self.cam_lyr.startEditing()
                self.cam_lyr.changeAttributeValue(feat.id(), trials_idx, 1000) 
                self.cam_lyr.commitChanges()

        lyr_name = "lines"
        gpkg_map_lines_lyr = f"{self.gpkg_path}|layername={lyr_name}"
        self.map_line_lyr = QgsVectorLayer(gpkg_map_lines_lyr, lyr_name, "ogr")
        self.map_line_lyr.loadNamedStyle(self.map_line_qml_path)

        lyr_name = "lines_img"
        gpkg_img_lines_lyr = f"{self.gpkg_path}|layername={lyr_name}"
        self.img_line_lyr = QgsVectorLayer(gpkg_img_lines_lyr, lyr_name, "ogr")
        self.img_line_lyr.loadNamedStyle(self.img_line_qml_path)       

        
        lyr_name = "gcps"
        gpkg_map_gcps_lyr = f"{self.gpkg_path}|layername={lyr_name}"
        self.map_gcps_lyr = QgsVectorLayer(gpkg_map_gcps_lyr, lyr_name, "ogr")
        # field_names = [field.name() for field in self.map_gcps_lyr.fields()]

        self.map_gcps_lyr = self.map_gcps_lyr
        self.map_gcps_lyr.loadNamedStyle(self.map_gcps_qml_path)       
        
        lyr_name = "gcps_img"
        gpkg_img_gcps_lyr = f"{self.gpkg_path}|layername={lyr_name}"
        self.img_gcps_lyr = QgsVectorLayer(gpkg_img_gcps_lyr, lyr_name, "ogr")
        self.img_gcps_lyr.loadNamedStyle(self.img_gcps_qml_path)       
        
        lyr_name = "lines_vx"
        gpkg_map_line_vx_lyr = f"{self.gpkg_path}|layername={lyr_name}"
        self.map_line_vx_lyr = QgsVectorLayer(gpkg_map_line_vx_lyr, lyr_name, "ogr")
        self.map_line_vx_lyr.loadNamedStyle(self.map_line_vx_qml_path)   
        
        #add missing fields to vertex layer in case they are not present
        map_line_pnts_pr = self.map_line_vx_lyr.dataProvider()
        field_names = [field.name() for field in map_line_pnts_pr.fields()]
        
        pot_fields = {"iid":QgsField("iid", QVariant.String),
                      "lid":QgsField("lid", QVariant.String),
                      "obj_x":QgsField("obj_x", QVariant.Double, "double", 10, 3),
                      "obj_y":QgsField("obj_y", QVariant.Double, "double", 10, 3),
                      "obj_z":QgsField("obj_z", QVariant.Double, "double", 10, 3),
                      "obj_x_std":QgsField("obj_x_std", QVariant.Double, "double", 10, 3),
                      "obj_y_std":QgsField("obj_y_std", QVariant.Double, "double", 10, 3),
                      "obj_z_std":QgsField("obj_z_std", QVariant.Double, "double", 10, 3),
                      "max_evec_dir":QgsField("max_evec_dir", QVariant.Double, "double", 10, 3),
                      "img_x": QgsField("img_x", QVariant.Double, "double", 5, 1),
                      "img_y": QgsField("img_y", QVariant.Double, "double", 5, 1),
                      "pval": QgsField("pval", QVariant.Double, "double", 3, 2)}
        
        add_fields = []        
        for name, qfield in pot_fields.items():
            if name not in field_names:
                add_fields.append(qfield)
        
        map_line_pnts_pr.addAttributes(add_fields)
        self.map_line_vx_lyr.updateFields() 
        
        map_line_pnts_pr = self.map_line_vx_lyr.dataProvider()
        field_names = [field.name() for field in map_line_pnts_pr.fields()]
                                    
        root = QgsProject.instance().layerTreeRoot()
        monoGroup = root.insertGroup(0, self.project_name)  
        monoGroup.addLayer(self.map_line_lyr) 
        monoGroup.addLayer(self.cam_lyr) 
        monoGroup.addLayer(self.reg_lyr)
        monoGroup.addLayer(self.map_gcps_lyr)
        monoGroup.addLayer(self.map_line_vx_lyr)
        
        #define layers which should be shown/considered in which canvas
        self.map_canvas.setLayers([self.map_line_lyr, self.cam_lyr, self.reg_lyr, self.map_gcps_lyr, self.map_line_vx_lyr])
        self.map_canvas.setExtent(self.reg_lyr.extent())
        self.map_canvas.refresh()
        
        self.dlg_main.setWindowTitle(self.project_name)
        self.crs = self.cam_lyr.crs()
        
        self.layer_collection = {"reg_lyr":self.reg_lyr,
                                 "cam_lyr":self.cam_lyr,
                                 "img_line_lyr":self.img_line_lyr,
                                 "img_gcps_lyr":self.img_gcps_lyr,
                                 "map_line_lyr":self.map_line_lyr,
                                 "map_gcps_lyr":self.map_gcps_lyr,
                                 "map_line_vx_lyr":self.map_line_vx_lyr}
        
        self.dlg_main.set_layers(self.layer_collection)
        self.dlg_main.activate_gui_elements()
        
        success = self.load_mesh()
        
        if success:
            self.load_cameras_from_gpkg()
        else:
            self.reset_plugin()
              
    def load_cameras_from_gpkg(self):
        
        cam_feats = self.cam_lyr.getFeatures() 
        for feat in cam_feats:
            
            feat_json = json.loads(QgsJsonUtils.exportAttributes(feat))
            del feat_json["fid"]
            cam = Camera(**feat_json)

            self.camera_collection[cam.iid] = cam
            self.dlg_main.add_camera_to_list(cam)
    
    def load_mesh(self):
        
        reg_feat = list(self.reg_lyr.getFeatures())[0]
        json_path = reg_feat["json_path"]

        if not os.path.exists(json_path):
            while True:
                upd_json_path = QFileDialog.getOpenFileName(None, "JSON not found! Please specify the new location.", "", ("JSON (*.json)"))[0]
                
                if upd_json_path == "":
                    break
                if os.path.exists(upd_json_path):
                    break
            
            if upd_json_path == "":
                QApplication.instance().restoreOverrideCursor()
                return False
            else:
                field_idx = self.reg_lyr.fields().indexOf('json_path')
                self.reg_lyr.startEditing()
                self.reg_lyr.changeAttributeValue(1,field_idx,upd_json_path)
                self.reg_lyr.commitChanges()
                json_path = upd_json_path
        
        
        with open(json_path, "r", encoding="utf-8") as f:
            tiles_data = json.load(f)
            tiles_data["tile_dir"] = os.path.normpath(os.path.join(os.path.dirname(json_path), "mesh"))
            tiles_data["op_dir"] = os.path.normpath(os.path.join(os.path.dirname(json_path), "op"))
        
        self.dlg_main.add_mesh_to_obj_canvas(tiles_data)
        return True
        
    def reset_plugin(self):
        
        root = QgsProject.instance().layerTreeRoot()
        
        #project_name is only set if anything was loaded; 
        #if its not available than we don't have to do anything
        if self.project_name:
            
            monoGroup = root.findGroup(self.project_name)
            if monoGroup:
                root.removeChildNode(monoGroup)
            
            # # self.clear_highlighted_features()    
            
            self.map_canvas.refresh()            
            self.map_canvas.setMapTool(self.map_pan_tool)
            
            self.dlg_main.setWindowTitle("moniQue")
        
    def open_main_dlg(self):
                
        self.dlg_main = MainDialog(plugin_dir=self.plugin_dir, parent=self)
        
        self.dlg_main.camera_collection = self.camera_collection
        self.dlg_main.load_project_signal.connect(self.on_load_project_signal)
        self.dlg_main.close_dialog_signal.connect(self.reset_plugin)
        
        #if QGIS shows the welcome screen setting the extent etc. does not work; 
        #with this workaround we check if a project is already openend (no welcome screen)
        #if not (if no layers were added) than we manually create a new project
        if len(QgsProject.instance().mapLayers()) == 0: 
            self.iface.newProject()
        
        self.dlg_main.show()

